fos_user_security:
    resource: "@zProjetsUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@zProjetsUserBundle/Resources/config/routing/profile.xml"
    prefix: /membre/profil

fos_user_register:
    resource: "@zProjetsUserBundle/Resources/config/routing/registration.xml"
    prefix: /

fos_user_resetting:
    resource: "@zProjetsUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reinitialisation-mot-de-passe

fos_user_change_password:
    resource: "@zProjetsUserBundle/Resources/config/routing/change_password.xml"
    prefix: /membre

fos_user_group:
    resource: "@zProjetsUserBundle/Resources/config/routing/group.xml"
    prefix: /groupe