security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /connexion
                use_forward:    false
                check_path:     /connexion
                failure_path:   null
                default_target_path: /
            logout:
                path:   /deconnexion
                target: /
            anonymous:    true

    access_control:
        - { path: /admin, roles: ROLE_ADMIN }