parameters:
#    z_projets_user.example.class: zProjets\UserBundle\Example

services:
#    z_projets_user.example:
#        class: %z_projets_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
